version: '3'

services:
  dbdstats:
    container_name: Basis
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      SENTRY_DSN: SENTRY_DSN_FOR_ERROR_REPORTING
      support_server: ID_OF_SUPPORTSERVER
      TOKEN: BOT_TOKEN
      OWNER_ID: DISCORD_ID_OF_OWNER
      LOG_LEVEL: INFO
    image: ghcr.io/serpensin/discordbots-basis
    volumes:
      - log:/app/Basis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
    log:
